# version: "3.9" # this is no longer respected, yay docker!
name: giglamesh

services:
  redroid:
    image: "redroid/redroid:14.0.0-latest"
    hostname: "redroid"
    ports:
      - "5555:5555/tcp"
    privileged: true  # required for redroid
    volumes:
      - "/mnt/doppelganger/redroid14-base:/data-base"
      - "/mnt/doppelganger/staging-diff:/data-diff"
    command:
      - "androidboot.use_redroid_overlayfs=1"
      - "androidboot.use_memfd=true"
  giglamesh:
    image: "ghcr.io/regulad/giglamesh:wayland"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5900:5900/tcp"
    devices:
      - /dev/dri  # privileged doesn't pass through the entire device; libdrm needs this and cage needs libdrm through wlroots
      - /dev/tty0 # same deal; this is required for libseat1 to run
    # the following 4 lines are absolutely necessary to get libseat working
    tty: true  # libseat1
    privileged: true  # libseat1
    read_only: true  # this is for security more than anything, we don't run any code from writeable areas of the container
    stdin_open: true  # unknown, but was unreliable without this
    volumes:
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /var/run
    depends_on:
      - "redroid"
    environment:
      DEVICE_IP: "redroid"
      DEVICE_ADB_PORT: "5555"
      VNC_USERNAME: ${VNC_USERNAME:-user}
      VNC_PASSWORD: ${VNC_PASSWORD:-password}
networks:
  default:
    driver: bridge
